### ISSUE TITLE
wrong colors generated

### ISSUE THREAD

**Issue by UserAbility** [UserAbility/metroid#12]
green pipes =P
<img width="703" alt="screen shot 2017-03-12 at 10 36 24 pm" src="https://cloud.githubusercontent.com/assets/3986650/23842878/c29e277c-0774-11e7-8b08-58a6f4617aac.png">

**Comment by theefxman** [comment]
![issues_fixed](https://cloud.githubusercontent.com/assets/4247833/23863720/6eeaacbc-07de-11e7-8aab-2478af1027c7.png)

I believe this issue is fixed in the next code release
